export const webPrivacy = {
  title: 'ePSA Web App — Privacy Policy',
  updated: 'July 23, 2026',
  sections: [
    {
      note: "This Privacy Policy is a working draft prepared for review by Mount Sinai's Office of General Counsel. It describes the application's current data handling in good faith but has not yet been reviewed or approved. Do not rely on this document as a final legal notice. The institutional Mount Sinai Privacy Policy at mountsinai.org/privacy continues to apply in parallel.",
      noteLabel: 'Draft for Mount Sinai counsel review:',
      noteType: 'info',
    },
    {
      title: 'About ePSA',
      text: 'ePSA (Prostate-Specific Awareness) is an educational and research tool owned and operated by the Department of Urology at the Icahn School of Medicine at Mount Sinai ("Mount Sinai", "we", "us", or "our"). The Principal Investigator is Ashutosh K. Tewari, MD. The cohort data underlying the ePSA risk models was collected under Mount Sinai GU Clinical IRB protocol STUDY-14-00050. ePSA is not a medical device, is not FDA-cleared, and is not a substitute for in-person medical evaluation.',
    },
    {
      title: 'Relationship to the Mount Sinai Privacy Policy',
      text: "ePSA is a Mount Sinai application. The institutional Mount Sinai Privacy Policy (available at mountsinai.org/privacy) is incorporated into this Privacy Policy by reference and continues to apply to your use of ePSA. This document supplements that policy with provisions specific to the ePSA tool. In the event of a direct conflict between this document and the institutional policy with respect to ePSA-specific data flows, the more protective provision controls.",
    },
    {
      title: 'Information We Collect',
      text: 'Depending on the storage option you select when using ePSA, we may collect the following categories of information:',
      list: [
        { label: 'Assessment inputs and results:', text: 'Your responses to the risk-assessment questions (including age, BMI, PSA value, IPSS and SHIM symptom scores, family history, self-reported ancestry, prior biopsy and MRI findings, and other clinical inputs) and the model outputs derived from them.' },
        { label: 'Contact identifiers:', text: 'ePSA does NOT collect an email address, phone number, or other contact identifier from users. Sign-in to ePSA uses an anonymous session key only, and the user record we create explicitly stores email and phone as null. There is no email- or phone-based sign-in path in the current production build.' },
        { label: 'Technical and usage data:', text: 'Standard server logs (IP address, browser type, request timestamps) generated by Firebase Hosting and Cloud Firestore for security, abuse prevention, and reliability. We do not currently deploy advertising trackers or third-party analytics SDKs on ePSA.' },
      ],
    },
    {
      title: 'How We Use Information',
      text: 'We use the information described above to compute and display your risk estimates; to allow you to retrieve a prior assessment across sessions; to operate, secure, and improve the ePSA tool; and, in a de-identified and aggregate form consistent with IRB protocol STUDY-14-00050, to support ongoing model validation and academic research. We do not sell your data and do not use it for commercial advertising.',
    },
    {
      title: 'Storage, Vendors, and HIPAA Status',
      text: "ePSA data is stored in Google Cloud Firestore (United States region) under Mount Sinai's Firebase project configuration. Firebase and Cloud Firestore are vendors to Mount Sinai. Firebase Authentication, Cloud Firestore, and related Firebase services are HIPAA-eligible only under an executed Google Cloud Business Associate Agreement (BAA); execution of the BAA covering this ePSA deployment is being finalized as part of Mount Sinai's review. Until that BAA is confirmed in writing, you should not enter information that you would consider Protected Health Information in a clinical setting. We do not share your ePSA data with third parties for marketing or advertising purposes.",
    },
    {
      title: 'Cookies and Tracking',
      text: 'ePSA uses a minimal set of cookies and similar local storage required to keep your anonymous session active (Firebase Authentication) and to remember your in-session preferences (such as text scale and language). ePSA does not use advertising cookies and does not currently transmit identifiable data to Google Analytics in its research configuration. If analytics are enabled in the future, they will be either de-identified to a tier-label only or gated behind explicit consent, and this Privacy Policy will be updated accordingly.',
    },
    {
      title: "Relationship to Mount Sinai's HIPAA Notice",
      text: "Mount Sinai maintains a separate Notice of Privacy Practices (NPP) under HIPAA covering its treatment, payment, and health-care-operations activities. ePSA is an educational and research tool and is not, in its current form, part of Mount Sinai's HIPAA-covered treatment workflow. Data entered into ePSA is therefore handled under this Privacy Policy and the IRB protocol governing the underlying study, not under the institutional NPP. For HIPAA questions specific to your clinical care at Mount Sinai, consult the institutional NPP.",
    },
    {
      title: 'Anonymous Session Keys',
      list: [
        { label: 'No email or phone collected:', text: 'Cloud storage uses an anonymous session key only. You receive a short random key (e.g. A1B2C3D4) to load your data later. We do not collect or store your email address or phone number, and the user record we create explicitly carries email and phone as null.' },
        { label: 'No identity linking:', text: 'Your assessment data is not linked to any identifier that could reveal who you are. Only someone with your session key can access that session’s data.' },
        { label: 'Save your key:', text: 'If you lose your session key, we cannot recover your data. We have no way to associate the data with you.' },
        { label: 'Local-only option:', text: 'You can also use ePSA with data stored only on this device ("This device only"), instead of the cloud, with no session key involved.' },
      ],
    },
    {
      title: 'Your Rights',
      text: 'You may request access to, correction of, or deletion of your ePSA data at any time, and you may withdraw from the educational and research use of ePSA without penalty and without affecting your access to clinical care at Mount Sinai. Depending on your place of residence, you may also have additional rights under state or international law (including the rights described in Mount Sinai’s institutional Privacy Policy under "Personal Data Rights").',
    },
    {
      title: "Children's Privacy",
      text: 'ePSA is intended for adult use only and is not directed to individuals under 18 years of age. We do not knowingly collect information from children. If you believe a child has provided information to ePSA, please contact the study team so the data can be deleted.',
    },
    {
      title: 'Changes to This Policy',
      text: 'We may update this Privacy Policy from time to time. The most recent version will be accessible from the ePSA footer. Continued use of ePSA after an update constitutes acknowledgement of the revised policy.',
    },
    {
      title: 'Contact',
      text: 'For ePSA-specific privacy questions, data-access or deletion requests, or to withdraw from the research and educational use of ePSA, contact the ePSA study team at aditya.dixit@mssm.edu (Aditya Dixit, ePSA research lead, Department of Urology, Icahn School of Medicine at Mount Sinai). For institutional Mount Sinai privacy matters, contact Compliance.info@mountsinai.org as described in the Mount Sinai Privacy Policy at mountsinai.org/privacy.',
    },
    {
      title: 'Related ePSA Apps',
      list: [
        { label: 'ePSA iOS App —', text: 'see /legal/ios/privacy' },
        { label: 'ePSA Android App —', text: 'see /legal/android/privacy' },
      ],
    },
  ],
};

export const webTerms = {
  title: 'ePSA Web App — Terms of Service',
  updated: 'July 23, 2026',
  sections: [
    {
      note: 'These Terms of Service are a working draft prepared for review by Mount Sinai’s Office of General Counsel. They describe the intended use of ePSA in good faith but have not yet been reviewed or approved. Do not rely on this document as a final legal agreement. The institutional Mount Sinai Terms and Conditions of Use continue to apply in parallel.',
      noteLabel: 'Draft for Mount Sinai counsel review:',
      noteType: 'info',
    },
    {
      title: 'Acceptance of Terms',
      text: 'By accessing or using ePSA, you agree to be bound by these Terms, by the ePSA Privacy Policy, and by the institutional Mount Sinai Terms and Conditions of Use. If you do not agree, do not access or use ePSA. You represent that you are at least 18 years of age and have the legal capacity to enter into these Terms.',
    },
    {
      title: "Relationship to Mount Sinai's Terms and Conditions of Use",
      text: 'ePSA is owned and operated by the Department of Urology at the Icahn School of Medicine at Mount Sinai ("Mount Sinai"). The institutional Mount Sinai Terms and Conditions of Use are incorporated into these Terms by reference and continue to apply to your use of ePSA. These Terms supplement that document with provisions specific to ePSA as a research and educational tool. In the event of a direct conflict between these Terms and the institutional Terms with respect to ePSA-specific functionality, the more restrictive provision controls.',
    },
    {
      title: 'Educational and Research Use Only',
      text: 'ePSA is an educational risk-assessment and research tool developed by Mount Sinai Urology in connection with IRB protocol STUDY-14-00050. ePSA is not a medical device, has not been cleared or approved by the U.S. Food and Drug Administration, and is intended to support — not replace — discussion with a qualified health-care provider. The risk models are internally validated only, against the Mount Sinai cohort described in the model documentation; no external validation cohort has been used to date.',
    },
    {
      title: 'The ePSA Tool Does Not Provide Medical Advice',
      text: 'The information and content in ePSA — including text, numerical scores, risk percentages, charts, and any printed or exported output — is for informational and research purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health-care provider with any questions you may have regarding your medical care, and never disregard professional medical advice or delay seeking it because of something you have read on or via ePSA. Reliance on any information appearing in ePSA is solely at your own risk.',
    },
    {
      title: 'Session Keys and Data Responsibility',
      text: 'Sign-in to ePSA uses an anonymous session key only. You are responsible for keeping your session key secure — anyone with the key can access the associated assessment data. If you lose your session key, the associated assessment data cannot be recovered, as we do not collect any contact information that would let us restore it. You may not use ePSA in a way that interferes with another user’s access, attempts to defeat security controls, or violates applicable law.',
    },
    {
      title: 'Intellectual Property',
      text: 'ePSA, its underlying models, source code, documentation, user interface, and content are the intellectual property of Mount Sinai and its content providers. You are granted a personal, non-exclusive, non-transferable, revocable, and limited right to use ePSA for personal, non-commercial educational purposes only. You may not copy, redistribute, decompile, reverse-engineer, or create derivative works of ePSA without Mount Sinai’s prior written consent.',
    },
    {
      title: 'No Warranty',
      text: 'ePSA is provided "as is" and "as available" without warranties of any kind, express or implied, including without limitation any implied warranty of merchantability, fitness for a particular purpose, non-infringement, accuracy, or fitness for clinical decision-making. Mount Sinai disclaims all such warranties. Mount Sinai does not warrant that ePSA will be uninterrupted or error-free, that defects will be corrected, or that the outputs of the risk models will be accurate or appropriate for your individual circumstances.',
    },
    {
      title: 'Limitation of Liability',
      text: 'To the maximum extent permitted by law, in no event shall Mount Sinai or any of its trustees, officers, faculty, employees, agents, investigators, or contractors be liable to you or any other party for any direct, indirect, incidental, special, punitive, or consequential damages arising out of or in connection with your use of, or inability to use, ePSA, including any damages related to a clinical decision influenced by ePSA outputs. Your sole and exclusive remedy for dissatisfaction with ePSA is to stop using it.',
    },
    {
      title: 'Indemnity',
      text: 'You agree to indemnify and hold harmless Mount Sinai and its trustees, officers, faculty, employees, agents, investigators, and contractors from any claim, demand, loss, or liability arising out of your breach of these Terms, your misuse of ePSA, or your reliance on ePSA outputs in a manner inconsistent with the educational and research purpose described above.',
    },
    {
      title: 'Changes to These Terms',
      text: 'Mount Sinai may revise these Terms from time to time without separate notice. The most recent version will be accessible from the ePSA footer. Continued use of ePSA after a revision constitutes acceptance of the revised Terms.',
    },
    {
      title: 'Governing Law',
      text: 'These Terms are governed by and construed in accordance with the laws of the State of New York, without regard to conflict-of-laws principles, consistent with the institutional Mount Sinai Terms and Conditions of Use.',
    },
    {
      title: 'Contact',
      text: 'For questions about these Terms or about the ePSA tool, contact the ePSA study team at aditya.dixit@mssm.edu (Aditya Dixit, ePSA research lead, Department of Urology, Icahn School of Medicine at Mount Sinai).',
    },
    {
      title: 'Related ePSA Apps',
      list: [
        { label: 'ePSA iOS App —', text: 'see /legal/ios/terms' },
        { label: 'ePSA Android App —', text: 'see /legal/android/terms' },
      ],
    },
  ],
};
